version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
    - mysql:/var/lib/mysql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: drupal7
      MYSQL_DATABASE: drupal7
      MYSQL_USER: drupal7
      MYSQL_PASSWORD: drupal7
  drupal7:
    depends_on:
    - db
    image: drupal:7.56-apache
    volumes:
    - modules:/var/www/html/modules
    - profiles:/var/www/html/profiles
    - sites:/var/www/html/sites
    - themes:/var/www/html/themes
    ports:
    - 8000:80
    restart: always
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: drupal7
      MYSQL_USER: drupal7
      MYSQL_PASSWORD: drupal7
volumes:
  mysql: null
  modules: null
  profiles: null
  sites: null
  themes: null