version: '3'

services:
   db:
     image: mariadb:latest
     volumes:
       - mysql:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: demo
       MYSQL_DATABASE: demo
       MYSQL_USER: demo
       MYSQL_PASSWORD: demo

volumes:
    mysql:

